In [ ]:
x={'sujana': 'sujananayak10@gmail.com', 'bill gates':'bill@gmail.com'}
x['bill gates']

'bill@gmail.com'

In [ ]:
x={'sujana': 'sujananayak10@gmail.com', 'bill gates':'bill@gmail.com'}
for name in x:
    print([name])

['sujana']
['bill gates']


In [ ]:
for email in x.values():
  print(email)

sujananayak10@gmail.com
bill@gmail.com


In [ ]:
for email in x:
  print(email)

sujana
bill gates


In [ ]:
for name in x.items():
  print(name)

('sujana', 'sujananayak10@gmail.com')
('bill gates', 'bill@gmail.com')


In [ ]:
for name,email in x.items():
  print(name)
  print(email)

sujana
sujananayak10@gmail.com
bill gates
bill@gmail.com


In [ ]:
x('sujana','nayak','sujananayak10@gmail.com','manipal')
fname,lname,email,cname=x

TypeError: ignored

In [ ]:
sales_record={
    'price':3.24,
    'num_items':4,
    'person': 'Sujana',
    'email': 'sujananayak10@gmail.com'

}

In [ ]:
sales_statement=' {} bought {} items at a price of INR {} each for a total of INR {} '

In [ ]:
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                              sales_record['num_items']*sales_record['price']
                             ))

 Sujana bought 4 items at a price of INR 3.24 each for a total of INR 12.96 


In [ ]:
import datetime as dt
import time as tm

In [ ]:
tm.time()


1693214123.4119177

In [ ]:
from datetime import date
from datetime import time
from datetime import datetime


In [ ]:
today=date.today()
print('date is',today)

date is 2023-08-28


In [ ]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2023, 8, 28, 9, 18, 44, 645050)

In [ ]:
dtnow.year, dtnow.month, dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2023, 8, 28, 9, 18, 44)

In [ ]:
delta=dt.timedelta(days=100)

datetime.timedelta(days=100)

In [ ]:
today=dt.date.today()


In [ ]:
today-delta

datetime.date(2023, 5, 20)

In [ ]:
today>today-delta

True

Object and map()

In [ ]:
class Person:
  institute="Manipal school of Information Science"


  def set_name(self,new_name):
    self.name=new_name
  def set_location(self,new_location):
    self.location=new_location

In [ ]:
person=Person()
person.set_name=("sujana")
person.set_location('Manipal, Udupi,Karnataka')


In [ ]:
print('{} lives in {} and is the studnent at the institute {}'.format(person.name,person.location))

In [ ]:
y={1,'x',2,'y',3}
y

{1, 2, 3, 'x', 'y'}

sets are unordered

In [ ]:
x={1,'x',2,'y',(1,2,3),'hello'}
x

{(1, 2, 3), 1, 2, 'hello', 'x', 'y'}

In [ ]:
type(x)

set

In [ ]:
x=[1,'x',2,'y']
type(x)


list

In [ ]:
store1=[10.00,11.00,12.32,5.34]
store2=[19.00,10.10,12.34,5.01]
store3=[15.00,12.00,11.00,6.00]
cheapest=map(min,store1,store2,store3)
costly=map(max,store1,store2,store3)
print(cheapest)

In [ ]:
for item in cheapest:
  print(item)

10.0
10.1
11.0
5.01


In [ ]:
for item in costly:
  print(item)

19.0
12.0
12.34
6.0


In [ ]:
def calculateSquare(n):
     return n*n

numbers=(1,2,3,4)
result=map(calculateSquare,numbers)
print(result)
res=list(result)
print(res)


[1, 4, 9, 16]


In [ ]:
res=list(result)
print(res)

[]


In [ ]:
for item in result:
  print(item)

In [ ]:
numbers=(1,2,3,4)

result=map(lambda x:x*x,numbers)
print(result)

In [ ]:
list(result)

[1, 4, 9, 16]

In [ ]:
num1=[4,5,6]
num2=[5,6,7]

In [ ]:
results=map(lambda n1,n2: n1+n2,num1,num2)
list(results)

[9, 11, 13]

In [ ]:
people=['python programming language','computer lab test','vinod scored A','kumar scored B']

def spilt_title_and_name(person):

  title=person.split()[0]
  lastname=person.split()[-1]
  return '{} {}'.format(title,lastname)

list(map(spilt_title_and_name,people))

['python language', 'computer test', 'vinod A', 'kumar B']

In [ ]:
for i in range(0,200):
    if(i%2!=0):
        print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
119
121
123
125
127
129
131
133
135
137
139
141
143
145
147
149
151
153
155
157
159
161
163
165
167
169
171
173
175
177
179
181
183
185
187
189
191
193
195
197
199


In [ ]:
import numpy as np


In [ ]:
lspace=np.linspace(0,9,10)
lspace

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
num=np.matrix([[11,121,34],
              [613,34,56],
              [32,78,67]])

In [ ]:
print('main diagonal element:\n',np.diag(num))
print('diagonal element above main diagonal',np.diag(num,1))


main diagonal element:
 [11 34 67]
diagonal element above main diagonal [121  56]


In [ ]:
p=np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])